
version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:12.14.0-browsers
    working_directory: ~/repo

jobs:
  test-and-build: 
    executor: my-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run test-with-coverage
      - run: APPLITOOLS_API_KEY=${APPLITOOLS_API_KEY} npm run appli-eyes
      - run: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build

  deploy-s3:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/repo/
      - run: sudo apt-get update && sudo apt-get install -y python-dev
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
      - run: sudo python get-pip.py
      - run: sudo pip install awscli --upgrade
      - run: aws s3 sync build/ s3://moneyflux.co.uk --delete

workflows:
  version: 2
  money-flux-ci:
    jobs:
      - test-and-build
      - deploy-s3:
          requires:
            - test-and-build
          filters:
            branches:
              only:
                - master
