version: 2
jobs:
  test-and-build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run: npm install
      - run: npm run test-with-coverage
      - run: npm run build
  deploy-s3:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run: npm install
      - run: sudo apt-get update && sudo apt-get install -y python-dev
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
      - run: sudo python get-pip.py
      - run: sudo pip install awscli --upgrade
      - run: npm run build
      - run: aws s3 sync build/ s3://moneyflux.co.uk --delete

workflows:
  version: 2
  test_and_build:
    jobs:
      - test-and-build
      - deploy-s3:
          requires:
            - test-and-build
          filters:
            branches:
              only:
                - master